# Generated by Django 2.1.2 on 2019-01-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_code_taggeditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ('-name',), 'verbose_name': 'code', 'verbose_name_plural': 'codes'},
        ),
    ]
