# Generated by Django 2.1.2 on 2019-01-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20190107_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='module',
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'customers'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
