# Generated by Django 2.1.2 on 2019-02-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_auto_20190219_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Person',
        ),
    ]
