# Generated by Django 2.1.2 on 2019-01-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_auto_20190108_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file_path', models.FileField(upload_to='templates/landing')),
                ('short_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='landtemps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.LandingTemplates'),
        ),
    ]
